# Generated by Django 2.2.9 on 2020-01-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Traduction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devis',
            name='assertmente',
        ),
        migrations.RemoveField(
            model_name='devis',
            name='is_assermented',
        ),
        migrations.AddField(
            model_name='user',
            name='assertmente',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='is_assermented',
            field=models.BooleanField(default=False),
        ),
    ]
