# Generated by Django 2.2.9 on 2020-01-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Traduction', '0003_auto_20200119_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='fichier',
            field=models.FileField(upload_to='files/Traduction/'),
        ),
    ]
