# Generated by Django 2.2.9 on 2020-01-24 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Traduction', '0004_auto_20200120_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.FloatField(default=0)),
                ('devis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Traduction.Devis')),
            ],
        ),
    ]
