# Generated by Django 2.2.9 on 2020-01-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Traduction', '0005_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='devis',
        ),
        migrations.AddField(
            model_name='user',
            name='notes',
            field=models.ManyToManyField(null=True, to='Traduction.Note'),
        ),
    ]
