# Generated by Django 2.2.9 on 2020-01-24 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Traduction', '0006_auto_20200124_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='notes',
            field=models.ManyToManyField(to='Traduction.Note'),
        ),
    ]
