# Generated by Django 2.2.9 on 2020-01-24 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Traduction', '0007_auto_20200124_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='devis',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Traduction.Devis'),
        ),
    ]
