# Generated by Django 2.2.9 on 2020-01-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Traduction', '0008_note_devis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devis',
            name='is_current',
        ),
        migrations.AddField(
            model_name='devis',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='devis',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
