# Generated by Django 2.2.9 on 2020-01-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Traduction', '0009_auto_20200125_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
