# Generated by Django 2.2.9 on 2020-01-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Traduction', '0012_devis_is_demanded'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='fichi_trad',
            field=models.FileField(null=True, upload_to='files/Traduisé/'),
        ),
    ]
