# Generated by Django 2.2.9 on 2020-01-26 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Traduction', '0013_devis_fichi_trad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='devis',
        ),
    ]
