# Generated by Django 2.2.9 on 2020-01-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Traduction', '0014_remove_note_devis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
