# Generated by Django 2.2.9 on 2020-01-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Traduction', '0016_auto_20200127_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='notes',
            field=models.ManyToManyField(blank=True, to='Traduction.Note'),
        ),
    ]
