# Generated by Django 2.2.9 on 2020-01-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Traduction', '0017_auto_20200127_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Telephone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='files/cvs/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='languages',
            field=models.ManyToManyField(blank=True, to='Traduction.Language'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(blank=True, choices=[('General', 'General'), ('Scientifque', 'Scientifque'), ('Web', 'Web')], max_length=11),
        ),
    ]
